name: terraform

on: [push]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Start localstack
      run: |
        docker run -d \
          -p 4566:4566 \
          -p 4571:4571 \
          --name localstack \
          localstack/localstack

    - name: Initialize terraform
      run: terraform init

    - name: Apply terraform
      run: terraform apply -auto-approve
