name: terraform

on: [push]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Start localstack
      run: docker run -d -p 4566:4566 -p 4571:4571 localstack/localstack

    - name: Initialize
      run: terraform init

    - name: Validate
      run: terraform validate

    - name: Plan
      run: terraform plan -out tfplan

    - name: Apply
      run: terraform apply tfplan -auto-approve

    - name: Show
      run: terraform show
